
%define where the detection files are
detectionDir = {...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp02',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp04',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp06',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp08',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp10',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp12',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp14',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp16',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp18',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp20',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp22',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp24',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp26',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp28',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp30',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp32',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp34',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp36',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp38',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp40',...
    };

%define the name of the detection file
detectionFileName = {...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    'detectionAll4.mat',...
    };

%define where the images are
imageDir = {...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp02',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp04',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp06',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp08',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp10',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp12',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp14',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp16',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp18',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp20',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp22',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp24',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp26',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp28',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp30',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp32',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp34',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp36',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp38',...
    '/home/kj35/orchestra/groups/lccb-receptors/Grinstein/Rich/110312_jasp_control/jasp40',...
    };

%define the name of the first image in a series
imageName = {...
    'jasp02_0001.tif',...
    'jasp04_0001.tif',...
    'jasp06_0001.tif',...
    'jasp08_0001.tif',...
    'jasp10_0001.tif',...
    'jasp12_0001.tif',...
    'jasp14_0001.tif',...
    'jasp16_0001.tif',...
    'jasp18_0001.tif',...
    'jasp20_0001.tif',...
    'jasp22_0001.tif',...
    'jasp24_0001.tif',...
    'jasp26_0001.tif',...
    'jasp28_0001.tif',...
    'jasp30_0001.tif',...
    'jasp32_0001.tif',...
    'jasp34_0001.tif',...
    'jasp36_0001.tif',...
    'jasp38_0001.tif',...
    'jasp40_0001.tif',...
    };

%calculate number of movies
numMovies = length(imageDir);

%initialize feature density and its standard deviation
featDensity = NaN(numMovies,2);

%go over all movies
for iMovie = 1 : numMovies
    
    %open the detection file
    load(fullfile(detectionDir{iMovie},detectionFileName{iMovie}));
    
    %open the image
    image = imread(fullfile(imageDir{iMovie},imageName{iMovie}));
    
    %find number of nonzero pixels
    cellArea = length(find(image~=0));
    
    %get number of features in each frame
    numFeat = NaN(size(movieInfo));
    for iFrame = 1 : size(movieInfo)
        numFeat(iFrame,1) = size(movieInfo(iFrame).xCoord,1);
    end
    
    %calculate mean and std of feature density
    featDensity(iMovie,:) = [mean(numFeat) std(numFeat)] / cellArea;
    
end